name: Upstream Sync

on:
  schedule:
    - cron: "0 */6 * * *" # 每6小时同步一次
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 取全量以便合并

      - name: Set Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync upstream changes via action
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          upstream_sync_repo: senshinya/MoonTV
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.PAT_TOKEN }}

      - name: Fallback manual merge if sync action failed
        if: failure()
        run: |
          echo "第三方同步 action 失败，执行手动 fetch & merge"
          git remote add upstream https://github.com/senshinya/MoonTV.git || true
          git fetch upstream
          git checkout main
          git merge upstream/main --no-edit || echo "已经是最新"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git main

      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 2
